from .fan_reward_wrapper import FanRewardWrapper
from .angle_reward_wrapper import AngleRewardWrapper
from .linear_angle_reward_wrapper import LinearAngleRewardWrapper
from .square_angle_reward_wrapper import SquareAngleRewardWrapper
from .tcheby_reward_wrapper import TchebychevRewardWrapper
from .fastrlap_wrapper import FastRLapWrapper

from .truncate_if_out_of_bounds_wrapper import TruncateIfOutOfBoundsWrapper