from .fan_reward_wrapper import FanRewardWrapper
from .angle_reward_wrapper import AngleRewardWrapper
from .car_reward_wrapper import CarRewardWrapper
from .linear_angle_reward_wrapper import LinearAngleRewardWrapper
from .exp_angle_reward_wrapper import ExponentialAngleRewardWrapper
from .tcheby_reward_wrapper import TchebychevRewardWrapper
from .fastrlap_wrapper import FastRLapWrapper
from .fastrlap_wrapper_old import OldFastRLapWrapper

from .terminate_if_out_of_bounds import TerminateIfOutOfBounds